// src/routes/about/+page.svelte
<script>
	import { background } from '../../store/background';
	import { showTitle } from '../../store/title';

	background.update(() => '#f3e87e');
	showTitle.update(() => true);
</script>

<svelte:head><title>About me — Felix Hoffmann</title></svelte:head>
<svelte:body class="background" />

<section>
	<img src="felix-hoffmann.webp" alt="Headshot of Felix Hoffmann" />
	<article>
		<h2>Hi!</h2>
		<p>I am passionate about web development, accessibility, and algorithms and data structures.</p>
		<p>
			Developing digital champions at <a
				href="https://iteratec.com"
				target="_blank"
				rel="noreferrer">iteratec</a
			>.
		</p>
		<p>Send me a message: <a href="mailto:hello@felixhoffmann.dev">hello@felixhoffmann.dev</a></p>
	</article>
</section>

<style>
	section {
		display: grid;
		grid-template-columns: 35% 5% 45% 15%;
	}

	img {
		max-width: 78%;
		align-self: end;
		filter: grayscale(100%);
		position: relative;
		bottom: -3rem;
		left: -3rem;
	}

	article {
		grid-row-start: 1;
		grid-column-start: 3;
		align-self: center;
	}

	h2,
	a {
		font-weight: 600;
	}

	p {
		font-weight: 300;
		margin: 1em 0;
	}

	h2,
	p {
		font-style: normal;
		font-size: 2rem;
		line-height: 140%;
	}

	@media (max-width: 899px) {
		section {
			grid-template-columns: 1rem calc(100% - 2rem) 1rem;
			grid-template-rows: 50% 50%;
		}

		img {
			grid-row-start: 2;
			grid-column-start: 1;
			grid-column-end: 3;
			max-height: 100%;
		}

		article {
			grid-row-start: 1;
			grid-column-start: 2;
		}

		h2,
		p {
			font-size: 1.2rem;
		}
	}
</style>

// src/app/about.tsx
import styles from './about.module.css';
import Image from 'next/image';

export default function About() {
    return (
        <section id={styles.about}>
            <div className={styles['p-wrapper']}>
                <h3>Hello! 👋</h3>
                <p>I am passionate about web development, algorithms and data structures, and accessibility.</p>
                <p>Developing digital champions at <a href="https://www.iteratec.com" target="_blank"
                    rel="noreferrer">iteratec</a>.</p>
                <p>Send me a message: <a href="mailto:hello@felixhoffmann.dev">hello@felixhoffmann.dev</a></p>
                <p className={[styles['socials-first'], styles.socials].join(' ')}>
                    <Image src="github-mark.svg" alt="" width="25" height="25"></Image><a href="https://github.com/zzzFelix" target="_blank" rel="noreferrer">GitHub</a></p>
                <p className={styles.socials}>
                    <Image src="/twitter-logo.svg" alt="" width="25" height="25"></Image><a href="https://twitter.com/felixmhoffmann" target="_blank" rel="noreferrer">Twitter</a>
                </p>
            </div>
            <div className={styles['img-wrapper']}>
                <Image src="/felixhoffmann.png" alt="Felix Hoffmann working on his laptop" className={styles.profile} width="200" height="200"></Image>
                <small>Image courtesy of Guntram Fechtig and <a href="https://agent.sh" target="_blank" rel="noreferrer">AgentConf</a>.</small>
            </div>
        </section>
    )
}
